services:
  - type: web
    name: LoCALIzate-api
    runtime: python
    repo: https://github.com/tuusuario/LoCALIzate-backend
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true